module.exports = (grunt) ->
  grunt.initConfig
    jekyll:
      build:
        options:
          src: 'web'
          dest: 'web/_site'
          config: 'web/_config.yml'

    'gh-pages':
      options:
        base: 'web/_site',
        repo: 'git@github.com:gregoryjscott/gregoryjscott.github.io.git'
        branch: 'master'
        message: 'Generated by me'
      src: ['**']

    connect:
      server:
        options:
          port: 4000
          base: 'web/_site'
          keepalive: true

  grunt.loadNpmTasks 'grunt-git'
  grunt.loadNpmTasks 'grunt-jekyll'
  grunt.loadNpmTasks 'grunt-contrib-clean'
  grunt.loadNpmTasks 'grunt-contrib-copy'
  grunt.loadNpmTasks 'grunt-contrib-connect'
  grunt.loadNpmTasks 'grunt-gh-pages'

  grunt.registerTask 'build', [
    'jekyll:build'
  ]
