title: TrainBuilder
desc: Windows Presentation Framework (WPF) application used by the Alaska
  Railroad to plan and schedule structure of their trains.
role: Developer
begin_year: 2007
end_year: 2007
_links:
  self:
    href: /projects/train-builder/
  languages:
    - href: /languages/cs/
    - href: /languages/sql/
  db:
    - href: /db/sql-server/
  os:
    - href: /os/windows/
  devices:
    - href: /devices/pc/
  jobs:
    - href: /jobs/rdi/
_embedded:
  languages:
    - title: C#
      desc: C# is a general-purpose, object-oriented programming language developed by
        Microsoft. It is used to develop a variety of applications, including
        web, mobile, desktop, and gaming applications. C# is based on the C and
        C++ programming languages, and it is designed to be simple, powerful,
        and type-safe. It supports both procedural and object-oriented
        programming paradigms, and it is used to create applications for the
        .NET framework. C# is a versatile language that can be used to create a
        wide range of applications.
      used_begin_year: 2004
      used_end_year: 2014
      _links:
        self:
          href: /languages/cs/
        projects:
          - href: /projects/agdc/
          - href: /projects/awwu-database-sync/
          - href: /projects/awwu-intranet/
          - href: /projects/awwu-job-scheduler/
          - href: /projects/awwu-systems-integration/
          - href: /projects/bit-proposal/
          - href: /projects/centroid/
          - href: /projects/cis-data-capture/
          - href: /projects/denver-schedules-api/
          - href: /projects/energy-efficiency-map/
          - href: /projects/flir-monitoring/
          - href: /projects/mvc-integration-test-framework/
          - href: /projects/please/
          - href: /projects/qb/
          - href: /projects/range-finding/
          - href: /projects/report-engine/
          - href: /projects/sar-reports/
          - href: /projects/scrum-tools/
          - href: /projects/sif-agent/
          - href: /projects/simpler/
          - href: /projects/somd/
          - href: /projects/systems-portal/
          - href: /projects/train-builder/
        jobs:
          - href: /jobs/independent/
          - href: /jobs/mas/
          - href: /jobs/rdi/
    - title: SQL
      desc: SQL (Structured Query Language) is a domain-specific language used in
        programming and designed for managing data held in a relational database
        management system (RDBMS). It is used to perform tasks such as
        retrieving, updating, inserting, and deleting data from a database. SQL
        is also used to create and modify database structures, such as tables,
        views, and stored procedures. It is a powerful language that can be used
        to query, analyze, and manipulate data.
      used_begin_year: 1999
      used_end_year: 2014
      _links:
        self:
          href: /languages/sql/
        projects:
          - href: /projects/agdc/
          - href: /projects/ahfc-integration/
          - href: /projects/awwu-database-sync/
          - href: /projects/awwu-intranet/
          - href: /projects/awwu-job-scheduler/
          - href: /projects/awwu-systems-integration/
          - href: /projects/cis-data-capture/
          - href: /projects/consumption-views/
          - href: /projects/denver-schedules-api/
          - href: /projects/employee-suggestions/
          - href: /projects/energy-efficiency-map/
          - href: /projects/please/
          - href: /projects/qb/
          - href: /projects/sar-reports/
          - href: /projects/scramble-score/
          - href: /projects/scrum-tools/
          - href: /projects/sif-agent/
          - href: /projects/somd/
          - href: /projects/systems-portal/
          - href: /projects/train-builder/
          - href: /projects/wengage-acct/
          - href: /projects/wengage-si/
        jobs:
          - href: /jobs/independent/
          - href: /jobs/mas/
          - href: /jobs/rdi/
  db:
    - title: SQL Server
      desc: SQL Server is a relational database management system (RDBMS) developed by
        Microsoft. It is used to store and manage data in a structured format,
        allowing users to query and manipulate the data using Structured Query
        Language (SQL). It is a powerful and reliable platform for data storage
        and management, and is used by many organizations for mission-critical
        applications. It is highly scalable and supports a wide range of
        features, including data replication, security, and high availability.
      used_begin_year: 2007
      used_end_year: 2014
      _links:
        self:
          href: /db/sql-server/
        projects:
          - href: /projects/agdc/
          - href: /projects/ahfc-integration/
          - href: /projects/energy-efficiency-map/
          - href: /projects/qb/
          - href: /projects/scrum-tools/
          - href: /projects/systems-portal/
          - href: /projects/train-builder/
        jobs:
          - href: /jobs/rdi/
  os:
    - title: Windows
      desc: Windows is a series of operating systems developed by Microsoft. It is the
        most popular operating system for personal computers, and is used in a
        variety of devices, including desktop and laptop computers, tablets, and
        smartphones. Windows provides a graphical user interface, allowing users
        to interact with their computer using a mouse and keyboard. It also
        includes a range of applications, such as web browsers, media players,
        and office suites. Windows also includes a range of security features,
        such as user accounts, firewalls, and antivirus software.
      used_begin_year: 1994
      used_end_year: 2021
      _links:
        self:
          href: /os/windows/
        projects:
          - href: /projects/agdc/
          - href: /projects/ahfc-integration/
          - href: /projects/awwu-database-sync/
          - href: /projects/awwu-intranet/
          - href: /projects/awwu-job-scheduler/
          - href: /projects/awwu-systems-integration/
          - href: /projects/bit-proposal/
          - href: /projects/centroid/
          - href: /projects/cis-data-capture/
          - href: /projects/class-scheduler/
          - href: /projects/consumption-views/
          - href: /projects/employee-suggestions/
          - href: /projects/energy-efficiency-map/
          - href: /projects/epic-ca-enrollment/
          - href: /projects/flir-monitoring/
          - href: /projects/mvc-integration-test-framework/
          - href: /projects/please/
          - href: /projects/qb/
          - href: /projects/range-finding/
          - href: /projects/report-engine/
          - href: /projects/sar-reports/
          - href: /projects/scrum-tools/
          - href: /projects/sif-agent/
          - href: /projects/simpler/
          - href: /projects/somd/
          - href: /projects/systems-portal/
          - href: /projects/train-builder/
          - href: /projects/wengage-acct/
          - href: /projects/wengage-si/
        jobs:
          - href: /jobs/fe/
          - href: /jobs/independent/
          - href: /jobs/mas/
          - href: /jobs/rdi/
        schools:
          - href: /schools/uco/
  devices:
    - title: PC
      desc: A personal computer (PC) is a general-purpose computing device built
        around a microprocessor, memory, storage and I/O interfaces, capable of
        running a broad range of operating systems and applications. Commonly
        used for software development, office productivity, web browsing and
        multimedia consumption, PCs provide a flexible, modular platform for
        both professional workflows and everyday tasks.
      used_begin_year: 1994
      used_end_year: 2014
      _links:
        self:
          href: /devices/pc/
        projects:
          - href: /projects/bit-proposal/
          - href: /projects/centroid/
          - href: /projects/please/
          - href: /projects/somd/
          - href: /projects/train-builder/
        jobs:
          - href: /jobs/rdi/
        schools:
          - href: /schools/uco/
  jobs:
    - title: Resource Data, Inc.
      desc: Technical Lead for Resource Data, Inc. (RDI), a consultancy specializing
        in custom database, web, and GIS programming services
      role: Technical Lead
      begin_year: 2005
      end_year: 2014
      time_desc: July 2005 - July 2014
      _links:
        self:
          href: /jobs/rdi/
        projects:
          - href: /projects/agdc/
          - href: /projects/ahfc-integration/
          - href: /projects/awwu-database-sync/
          - href: /projects/awwu-intranet/
          - href: /projects/awwu-job-scheduler/
          - href: /projects/awwu-systems-integration/
          - href: /projects/bit-proposal/
          - href: /projects/centroid/
          - href: /projects/cis-data-capture/
          - href: /projects/consumption-views/
          - href: /projects/employee-suggestions/
          - href: /projects/energy-efficiency-map/
          - href: /projects/flir-monitoring/
          - href: /projects/please/
          - href: /projects/qb/
          - href: /projects/range-finding/
          - href: /projects/report-engine/
          - href: /projects/sar-reports/
          - href: /projects/scramble-score/
          - href: /projects/scrum-tools/
          - href: /projects/somd/
          - href: /projects/systems-portal/
          - href: /projects/train-builder/
        languages:
          - href: /languages/cs/
          - href: /languages/css/
          - href: /languages/html/
          - href: /languages/js/
          - href: /languages/py/
          - href: /languages/rb/
          - href: /languages/sql/
        db:
          - href: /db/access/
          - href: /db/oracle/
          - href: /db/postgres/
          - href: /db/sql-server/
          - href: /db/sqlite/
        tools:
          - href: /tools/backbone/
          - href: /tools/jenkins/
        os:
          - href: /os/linux/
          - href: /os/macos/
          - href: /os/windows/
        devices:
          - href: /devices/android/
          - href: /devices/cloud/
          - href: /devices/gps/
          - href: /devices/iphone/
          - href: /devices/laser/
          - href: /devices/mac/
          - href: /devices/pc/
          - href: /devices/range-finder/
          - href: /devices/server/